# This is a basic workflow to help you get started with Actions

name: sturdy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the

    #关键配置
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actionseckout@v2
      - name: install node.js
        uses: actionstup-node@v3.0.0
        with:
          node-version: "16.X"
      - name: package
        run: sh build.sh -v 0
#       - name: copy file via ssh key
#         uses: appleboy/scp-action@master
#         with:
#           #需要部署的文件地址
#           source: "output/*"
#           # SSH address  服务器地址
#           host: ${{ secrets.REMOTE_HOST }}
#           # Remote dir path  服务器下部署文件存放路径
#           target: ~/tmp
#           # SSH Port  服务器端口
#           port: 22
#           # SSH User name   用户名
#           username: ${{ secrets.USER_NAME }}
#           # SSH User password  用户密码
#           password: ${{ secrets.PASSWORD }}

      - name: deploy
        uses: mdallasanta/ssh-scp-deploy@{version}
        with:
          local: './output/*'                                                  # Local file path - REQUIRED false - DEFAULT ./
          remote: '~/tmp'                                                 # Remote file path - REQUIRED false - DEFAULT ~/
          host: ${{secrets.REMOTE_HOST}}                                      # Remote server address - REQUIRED true
          port: 22                                    # Remote server port - REQUIRED false - DEFAULT 22
          user: ${{secrets.USER_NAME}}                                      # Remote server user - REQUIRED true
          password: ${{secrets.PASSWORD}}                              # User password - REQUIRED at least one of "password" or "key"                                   
          post_upload: | 
                cd ~/project/minor/bin
                sh vpm.sh install -a sturdy -d ~/tmp/output/sturdy-0.0.1.0.tar.gz
                pm2 restart minor
