name: Deploy site files

on:
  push:
    branches:
      - main # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      - uses: actions/checkout@v2 # 第一步，下载代码仓库

      - name: package
        run: sh build.sh -v 0

      - name: copy file
        uses: appleboy/scp-action@master
        with:
                host: ${{ secrets.REMOTE_HOST }}
                username: ${{ secrets.USER_NAME }}
                password: ${{ secrets.PASSWORD }}
                port: 22
                source: "./output/*"
                target: "~/tmp"
                
      - name: Restart server # 第三步，重启服务
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }} # 下面三个配置与上一步类似
          username: ${{ secrets.USER_NAME }}
          password : ${{ secrets.PASSWORD }}
          port: 22
          # 重启的脚本，根据自身情况做相应改动，一般要做的是migrate数据库以及重启服务器
          script: |
                cd ~/project/minor/bin
                sh vpm.sh install -a sturdy -d ~/tmp/output/sturdy-0.0.1.0.tar.gz
                pm2 restart minor
